apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example
bases:
- ../base/local
#- github.com/utilitywarehouse/thanos-manifests/base/local
patchesStrategicMerge:
- thanos-rule.yaml
- thanos-compact.yaml
- prometheus.yaml
- prometheus-secrets.yaml
