apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  annotations:
    vault.uw.systems/aws-role: "arn:aws:iam::000000000000:role/example-role"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  template:
    metadata:
      annotations:
        uw.systems/kyverno-inject-sidecar-request: vault-sidecar-aws
    spec:
      containers:
        - name: prometheus
          env:
            - name: PROMETHEUS_URL
              value: "https://prometheus.overlay.aws.example.com"
