apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-receive
  annotations:
    vault.uw.systems/aws-role: "arn:aws:iam::000000000000:role/example-role"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-receive
spec:
  template:
    metadata:
      annotations:
        uw.systems/kyverno-inject-sidecar-request: vault-sidecar-aws
