apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-rule
spec:
  template:
    spec:
      containers:
      - name: thanos-rule
        env:
        - name: ALERTMANAGER_URL
          value: "dns+http://alertmanager.overlay-namespace"
        - name: THANOS_QUERY_URL
          value: "https://thanos-query.overlay.example.com"
