apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-compact
  annotations:
    vault.uw.systems/aws-role: "arn:aws:iam::000000000000:role/example-role"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-compact
spec:
  template:
    metadata:
      annotations:
        injector.tumblr.com/request: vault-sidecar-aws
