apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus.yaml
images:
  - name: prometheus
    newName: prom/prometheus
    newTag: v2.53.1
  - name: thanos
    newName: quay.io/thanos/thanos
    newTag: 0.36.0-rc.0 #https://github.com/thanos-io/thanos/pull/7403
labels:
  - includeSelectors: true
    pairs:
      service: monitoring
