apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus.yaml
images:
  - name: prometheus
    newName: prom/prometheus
    newTag: v2.52.0
  - name: thanos
    newName: quay.io/thanos/thanos
    newTag: v0.35.1
labels:
  - includeSelectors: true
    pairs:
      service: monitoring
