apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - thanos-compact.yaml
images:
  - name: thanos
    newName: quay.io/thanos/thanos
    newTag: v0.36.0-rc.0 # https://github.com/thanos-io/thanos/pull/7403
labels:
  - includeSelectors: true
    pairs:
      service: monitoring
