apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - thanos-compact.yaml
images:
  - name: thanos
    newName: quay.io/thanos/thanos
    newTag: v0.37.1
labels:
  - includeSelectors: true
    pairs:
      service: monitoring
