apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - memcached-peers-svc.yaml
  - memcached.yaml
  - thanos-store.yaml
patches:
  - path: memcached-resource-patch.yaml
images:
  - name: thanos
    newName: quay.io/thanos/thanos
    newTag: main-2024-06-11-8ec0c24 # https://github.com/thanos-io/thanos/pull/7403
labels:
  - includeSelectors: true
    pairs:
      service: monitoring
