apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  service: monitoring
resources:
  - memcached-peers-svc.yaml
  - memcached.yaml
  - thanos-store.yaml
patches:
  - path: memcached-resource-patch.yaml
images:
  - name: thanos
    newName: quay.io/thanos/thanos
    newTag: v0.32.2
