---
# Source: memcached/templates/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: thanos-store-memcached
  labels:
    app.kubernetes.io/instance: thanos-store
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: memcached
    app.kubernetes.io/version: 1.6.38
    helm.sh/chart: memcached-7.8.1
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: thanos-store
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: memcached
      app.kubernetes.io/version: 1.6.38
      helm.sh/chart: memcached-7.8.1
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - ports:
        - port: 11211
---
# Source: memcached/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: thanos-store-memcached
  labels:
    app.kubernetes.io/instance: thanos-store
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: memcached
    app.kubernetes.io/version: 1.6.38
    helm.sh/chart: memcached-7.8.1
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: thanos-store
      app.kubernetes.io/name: memcached
---
# Source: memcached/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: thanos-store-memcached
  labels:
    app.kubernetes.io/instance: thanos-store
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: memcached
    app.kubernetes.io/version: 1.6.38
    helm.sh/chart: memcached-7.8.1
---
# Source: memcached/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: thanos-store-memcached
  labels:
    app.kubernetes.io/instance: thanos-store
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: memcached
    app.kubernetes.io/version: 1.6.38
    helm.sh/chart: memcached-7.8.1
spec:
  type: ClusterIP
  ports:
    - name: memcache
      port: 11211
      targetPort: memcache
      nodePort: null
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: thanos-store
    app.kubernetes.io/name: memcached
---
# Source: memcached/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store-memcached
  labels:
    app.kubernetes.io/instance: thanos-store
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: memcached
    app.kubernetes.io/version: 1.6.38
    helm.sh/chart: memcached-7.8.1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: thanos-store
      app.kubernetes.io/name: memcached
  replicas: 2
  podManagementPolicy: "Parallel"
  serviceName: thanos-store-memcached
  updateStrategy:
    rollingUpdate: {}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: thanos-store
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: memcached
        app.kubernetes.io/version: 1.6.38
        helm.sh/chart: memcached-7.8.1
      annotations:
    spec:
      
      automountServiceAccountToken: false
      affinity:
        podAffinity:
          
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: thanos-store
                    app.kubernetes.io/name: memcached
                topologyKey: kubernetes.io/hostname
              weight: 1
        nodeAffinity:
          
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      serviceAccountName: thanos-store-memcached
      enableServiceLinks: true
      initContainers:
      containers:
        - name: memcached
          image: docker.io/bitnami/memcached:1.6.38-debian-12-r4
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          args:
            - /run.sh
            - --memory-file=/cache-state/memory_file
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MEMCACHED_PORT_NUMBER
              value: "11211"
          ports:
            - name: memcache
              containerPort: 11211
          livenessProbe:
            failureThreshold: 6
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            exec:
              command:
                - pgrep
                - memcached
          readinessProbe:
            failureThreshold: 6
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
            tcpSocket:
              port: memcache
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -ec
                  - |
                    /usr/bin/pkill -10 memcached
                    sleep 60s
          resources:
            limits:
              cpu: 2
              memory: 1Gi
          volumeMounts:
            - name: data
              mountPath: /cache-state
            - name: empty-dir
              mountPath: /opt/bitnami/memcached/conf
              subPath: app-conf-dir
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
      volumes:
        - name: empty-dir
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/instance: thanos-store
          app.kubernetes.io/name: memcached
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "10Gi"
