apiVersion: v1
kind: Service
metadata:
  name: thanos-store-memcached-peers
  labels:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/instance: thanos-store
  annotations:
spec:
  clusterIP: None
  sessionAffinity: None
  ports:
    - name: memcache
      port: 11211
      targetPort: memcache
      nodePort: null
  selector:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/instance: thanos-store
