apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store-memcached
spec:
  template:
    spec:
      containers:
        - name: memcached
          resources:
            requests:
              cpu: 0m
              memory: 8Mi
