# https://github.com/thanos-io/kube-thanos/blob/main/examples/all/manifests/thanos-store-statefulSet.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "10902"
    prometheus.io/scrape: "true"
  labels:
    app: thanos-store
  name: thanos-store
spec:
  ports:
    - port: 10901
      protocol: TCP
      targetPort: grpc
  selector:
    app: thanos-store
  sessionAffinity: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-store
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store
  labels:
    app: thanos-store
    app.kubernetes.io/name: thanos-store
spec:
  podManagementPolicy: Parallel
  replicas: 2
  serviceName: thanos-store
  selector:
    matchLabels:
      app: thanos-store
      app.kubernetes.io/name: thanos-store
  template:
    metadata:
      labels:
        app: thanos-store
        app.kubernetes.io/name: thanos-store
    spec:
      serviceAccountName: thanos-store
      containers:
        - name: thanos-store
          image: thanos
          args:
            - store
            - --log.level=warn
            - --data-dir=/var/thanos/store
            - --objstore.config-file=/etc/thanos/config.yaml
            - |-
              --index-cache.config="config":
                "addresses":
                - "dnssrv+_memcache._tcp.$(MEMCACHED_SVC)"
                "dns_provider_update_interval": "10s"
                "max_async_buffer_size": 100000
                "max_async_concurrency": 100
                "max_get_multi_batch_size": 0
                "max_get_multi_concurrency": 100
                "max_idle_connections": 100
                "max_item_size": "1MiB"
                "timeout": "500ms"
              "type": "memcached"
            - |-
              --store.caching-bucket.config="blocks_iter_ttl": "5m"
              "chunk_object_attrs_ttl": "24h"
              "chunk_subrange_size": 16000
              "chunk_subrange_ttl": "24h"
              "config":
                "addresses":
                - "dnssrv+_memcache._tcp.$(MEMCACHED_SVC)"
                "dns_provider_update_interval": "10s"
                "max_async_buffer_size": 100000
                "max_async_concurrency": 100
                "max_get_multi_batch_size": 0
                "max_get_multi_concurrency": 100
                "max_idle_connections": 100
                "max_item_size": "1MiB"
                "timeout": "500ms"
              "max_chunks_get_range_requests": 3
              "metafile_content_ttl": "24h"
              "metafile_doesnt_exist_ttl": "15m"
              "metafile_exists_ttl": "2h"
              "metafile_max_size": "1MiB"
              "type": "memcached"
            - |
               --tracing.config=type: OTLP
               config:
                 client_type: "grpc"
                 insecure: true
                 endpoint: "dns:///otel-collector.otel:4317"
                 resource_attributes:
                   k8s.namespace.name: "$(POD_NAMESPACE)"
                   uw.team: "system"
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: "MEMCACHED_SVC"
              value: "thanos-store-memcached-peers"
          ports:
            - name: http
              containerPort: 10902
            - name: grpc
              containerPort: 10901
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
              scheme: HTTP
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 25
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
              scheme: HTTP
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 10
            failureThreshold: 25
          volumeMounts:
            - name: data
              mountPath: /var/thanos/store
            - name: thanos-storage
              mountPath: /etc/thanos
          resources:
            requests:
              cpu: 0m
              memory: 64Mi
            limits:
              cpu: 4000m
              memory: 4000Mi
      securityContext:
        fsGroup: 1001
      volumes:
        - name: thanos-storage
          configMap:
            name: thanos-storage
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
