apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-rule
spec:
  template:
    spec:
      initContainers:
        - name: git-mirror
          image: quay.io/utilitywarehouse/git-mirror:v0.3.0
          imagePullPolicy: Always
          restartPolicy: Always
          ports:
            - name: metrics
              containerPort: 9001
              protocol: TCP
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: "0"
              memory: 32Mi
          startupProbe:
            tcpSocket:
              port: 9001
            # max 300s (30 * 5) to finish its initial sync.
            failureThreshold: 60
            periodSeconds: 5
          volumeMounts:
            - name: data
              mountPath: /var/thanos/data/git-mirror
              subPath: git-mirror
            - name: data
              mountPath: /var/thanos/rule-templates/git-mirror
              subPath: git-mirror/links
        - name: rule-watcher
          volumeMounts:
            # rules synced via git-mirror in /var/thanos/rule-templates
            # will be symlinked to /var/thanos/data/xxxx
            - name: data
              mountPath: /var/thanos/data/git-mirror
              subPath: git-mirror
            - name: data
              mountPath: /var/thanos/rule-templates/git-mirror
              subPath: git-mirror/links
