apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  template:
    spec:
      initContainers:
        - name: git-mirror
          image: quay.io/utilitywarehouse/git-mirror:v0.3.8
          imagePullPolicy: Always
          restartPolicy: Always
          ports:
            - name: http
              containerPort: 9001
              protocol: TCP
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: "0"
              memory: 32Mi
          startupProbe:
            tcpSocket:
              port: 9001
            # max 300s (60 * 5) to finish its initial sync.
            failureThreshold: 60
            periodSeconds: 5
          volumeMounts:
            - name: prometheus
              mountPath: /prometheus/git-mirror
              subPath: git-mirror
            - name: prometheus
              mountPath: /var/prometheus/rule-templates/git-mirror
              subPath: git-mirror/links
        - name: rule-watcher
          volumeMounts:
            # rules synced via git-mirror in /var/prometheus/rule-templates
            # will be symlinked to /var/prometheus/xxxx
            - name: prometheus
              mountPath: /prometheus/git-mirror
              subPath: git-mirror
            - name: prometheus
              mountPath: /var/prometheus/rule-templates/git-mirror
              subPath: git-mirror/links
