apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    kubernetes.io/ingress.class: traefik-private
  name: global-thanos-query
  namespace: sys-mon
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: global-thanos-query
  name: global-thanos-query
  namespace: sys-mon
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "10902"
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: http
    name: http
  selector:
    app: global-thanos-query
  sessionAffinity: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: global-thanos-query
  namespace: sys-mon
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: global-thanos-query
  namespace: sys-mon
  labels:
    app: global-thanos-query
spec:
  replicas: 2
  selector:
    matchLabels:
      app: global-thanos-query
  template:
    metadata:
      labels:
        app: global-thanos-query
    spec:
      containers:
      - name: global-thanos-query
        image: improbable/thanos:master-2019-05-31-a7b47542
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/healthy
            port: http
            scheme: HTTP
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/healthy
            port: http
            scheme: HTTP
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - name: config
          mountPath: /etc/thanos
      volumes:
      - name: config
        configMap:
          name: global-thanos-query
