apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  labels:
    kubernetes.io/ingress.class: traefik-private
  annotations:
    external-dns.alpha.kubernetes.io/target: private-ingress.environment.domain
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  template:
    spec:
      containers:
      - name: thanos-sidecar
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/secrets/service-account/credentials.json"
        volumeMounts:
        - name: gcp-credentials
          mountPath: /etc/secrets/service-account/credentials.json
          subPath: credentials.json
      volumes:
      - name: gcp-credentials
        secret:
          secretName: thanos-storage
