apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store
  labels:
    app: thanos-store
spec:
  template:
    spec:
      containers:
      - name: thanos-store
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/secrets/service-account/credentials.json"
        volumeMounts:
        - name: gcp-credentials
          mountPath: /etc/secrets/service-account/credentials.json
          subPath: credentials.json
      volumes:
      - name: gcp-credentials
        secret:
          secretName: thanos-storage
