apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - thanos-receive.yaml
images:
  - name: thanos
    newName: quay.io/thanos/thanos
    newTag: v0.32.2
labels:
  - includeSelectors: true
    pairs:
      service: monitoring
