apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-rule
spec:
  template:
    spec:
      initContainers:
        - name: rule-watcher
          image: alpine
          restartPolicy: Always
          command: ["/bin/sh", "/scripts/rule-watcher"]
          env:
            - name: RELOAD_PORT
              value: "10902"
            - name: RENDERED_RULES_PATH
              value: /var/thanos/rules
            - name: TEMPLATED_RULES_PATH
              value: /var/thanos/rule-templates
          volumeMounts:
            - name: rules-rendered
              mountPath: /var/thanos/rules
            - name: rule-watcher
              mountPath: /scripts
      containers:
        - name: thanos-rule
          volumeMounts:
            - name: rules-rendered
              mountPath: /var/thanos/rules
      volumes:
        - name: rule-watcher
          configMap:
            name: rule-watcher
        - name: rules-rendered
          emptyDir: {}
