apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "10902"
    prometheus.io/scrape: "true"
  labels:
    app: thanos-rule
  name: thanos-rule
spec:
  ports:
    - port: 10902
      protocol: TCP
      targetPort: http
      name: http-rule
    - port: 10901
      protocol: TCP
      targetPort: grpc
      name: grpc-rule
  selector:
    app: thanos-rule
  sessionAffinity: None
  clusterIP: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: thanos-rule
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-rule
  labels:
    app: thanos-rule
    app.kubernetes.io/name: thanos-rule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thanos-rule
      app.kubernetes.io/name: thanos-rule
  serviceName: thanos-rule
  template:
    metadata:
      labels:
        app: thanos-rule
        app.kubernetes.io/name: thanos-rule
    spec:
      serviceAccountName: thanos-rule
      containers:
        - name: thanos-rule
          image: thanos
          args:
            - rule
            - --log.level=warn
            - --data-dir=/var/thanos/data/
            - --rule-file=/var/thanos/rules/*.yaml
            - --rule-file=/var/thanos/recording/*.yaml
            - --alertmanagers.config-file=/etc/alertmanager/config.yaml
            - --eval-interval=30s
            - --alert.label-drop="replica"
            - --alert.label-drop="rule_replica"
            - --alert.query-url=$(THANOS_QUERY_URL)
            - --query.sd-files=/etc/thanos/query-sd.yaml
            - --label=cloud_provider="$(CLOUD_PROVIDER)"
            - --label=cluster="$(KUBERNETES_CLUSTER)"
            - --label=kubernetes_cluster="$(KUBERNETES_CLUSTER)"
            - --label=provider="$(CLOUD_PROVIDER)"
            - --label=replica="$(POD_NAME)"
            - --label=rule_replica="$(POD_NAME)"
            - --label=uw_environment="$(UW_ENVIROMENT)"
            - --objstore.config-file=/etc/thanos/config.yaml
          env:
            - name: ALERTMANAGER_URL
              value: "dns+http://alertmanager.base-namespace"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            # external URL for rendering inside alerts
            - name: THANOS_QUERY_URL
              value: "https://thanos-query.base.example.com"
          ports:
            - name: http
              containerPort: 10902
            - name: grpc
              containerPort: 10901
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
              scheme: HTTP
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
              scheme: HTTP
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 10
            failureThreshold: 5
          volumeMounts:
            - name: data
              mountPath: /var/thanos/data
            - name: rules
              mountPath: /var/thanos/rules
            - name: config
              mountPath: /etc/thanos/query-sd.yaml
              subPath: query-sd.yaml
            - name: thanos-storage
              mountPath: /etc/thanos/config.yaml
              subPath: config.yaml
            - name: am-config
              mountPath: /etc/alertmanager
          resources:
            requests:
              cpu: "0"
              memory: 64Mi
            limits:
              cpu: "4"
              memory: 500Mi
      securityContext:
        fsGroup: 1001
      volumes:
        - name: rules
          configMap:
            defaultMode: 420
            name: alerts
        - name: config
          configMap:
            name: thanos-rule
        - name: thanos-storage
          configMap:
            name: thanos-storage
        - name: am-config
          secret:
            secretName: thanos-rule-alertmanager
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
