apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  template:
    spec:
      initContainers:
        - name: rule-watcher
          image: alpine
          restartPolicy: Always
          command: ["/bin/sh", "/scripts/rule-watcher"]
          env:
            - name: RELOAD_PORT
              value: "9090"
            - name: RENDERED_RULES_PATH
              value: /var/prometheus/rules
            - name: TEMPLATED_RULES_PATH
              value: /var/prometheus/rule-templates
          startupProbe:
            exec:
              command:
                - test
                - -e
                - /var/prometheus/rules/rule-watcher-rules-ready
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: rules-rendered
              mountPath: /var/prometheus/rules
            - name: rule-watcher
              mountPath: /scripts
      containers:
        - name: prometheus
          volumeMounts:
            - name: rules-rendered
              mountPath: /var/prometheus/rules
      volumes:
        - name: rule-watcher
          configMap:
            name: rule-watcher
        - name: rules-rendered
          emptyDir: {}
