apiVersion: apps/v1
kind: Deployment
metadata:
  name: global-thanos-query
spec:
  selector:
    matchLabels:
      app: global-thanos-query
  template:
    metadata:
      labels:
        app: global-thanos-query
    spec:
      containers:
      - name: global-thanos-query
        args:
        - query
        - --log.level=info
        - --query.replica-label=replica
        - --store.sd-files=/etc/thanos/store-sd.yaml
        - --grpc-client-tls-secure
        resources:
          requests:
            cpu: 50m
            memory: 500Mi
          limits:
            memory: 5000Mi
