apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
spec:
  template:
    spec:
      containers:
      - name: thanos-query
        args:
        - query
        - --log.level=info
        - --query.replica-label=replica
        - --store.sd-files=/etc/thanos/store-sd.yaml
        - --query.timeout=5m
        - --store.response-timeout=15s
        resources:
          requests:
            cpu: 50m
            memory: 500Mi
          limits:
            memory: 8000Mi
