apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9001"
    prometheus.io/scrape: "true"
  name: prometheus-git-mirror-metrics
spec:
  ports:
    - port: 9001
      protocol: TCP
      targetPort: metrics
      name: metrics
  selector:
    app: thanos-rule
