# Headless Services used for webhook
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9001"
    prometheus.io/scrape: "true"
  name: thanos-git-mirror
spec:
  ports:
    - port: 9001
      protocol: TCP
      targetPort: http
      name: http
  selector:
    app: thanos-rule
  sessionAffinity: None
  clusterIP: None
