apiVersion: v1
kind: ConfigMap
metadata:
  name: alerts
data:
  meta.yaml: |-
    groups:
    - name: meta
      rules:
      - alert: DeadMansSwitch
        expr: vector(1)
        labels:
          severity: critical
        annotations:
          description: This is a DeadMansSwitch meant to ensure that the entire Alerting
            pipeline is functional.
          summary: Alerting DeadMansSwitch
