apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  service: monitoring
resources:
- prometheus.yaml
- thanos-compact.yaml
- thanos-query.yaml
- thanos-rule.yaml
- thanos-store.yaml
