apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: prometheus-secrets
stringData:
  config.yaml: |
    type: S3
    config:
      bucket: bucket-name
      endpoint: s3.eu-west-5.amazonaws.com
      encrypt_sse: true
      access_key: ""
      secret_key: ""
