apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: thanos-storage
data:
  # Base64 decoding this will show the secret structure
  # More examples are at: https://improbable-eng.github.io/thanos/storage.md/
  config.yaml: dHlwZTogUzMKICAgIGNvbmZpZzoKICAgICAgYnVja2V0OiBidWNrZXQtbmFtZQogICAgICBlbmRwb2ludDogczMuZXUtd2VzdC01LmFtYXpvbmF3cy5jb20KICAgICAgZW5jcnlwdF9zc2U6IHRydWUKICAgICAgYWNjZXNzX2tleTogIiIKICAgICAgc2VjcmV0X2tleTogIiI=
