apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    kubernetes.io/ingress.class: traefik-private
  name: thanos-query
spec:
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    kubernetes.io/ingress.class: traefik-private-tls
  annotations:
    ingress.kubernetes.io/protocol: h2c
  name: thanos-query-api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: thanos-query
  name: thanos-query
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-query
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  labels:
    app: thanos-query
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      containers:
      - name: thanos-query
        image: improbable/thanos:master-2019-05-31-a7b47542
        args:
        - query
        - --log.level=info
        - --query.replica-label=replica
        - --store.sd-files=/etc/thanos/store-sd.yaml
        - --query.timeout=5m
        - --store.response-timeout=15s
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/healthy
            port: http
            scheme: HTTP
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/healthy
            port: http
            scheme: HTTP
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 50m
            memory: 500Mi
          limits:
            memory: 8000Mi
        volumeMounts:
        - name: config
          mountPath: /etc/thanos
      volumes:
      - name: config
        configMap:
          name: thanos-query
