apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "10902"
    prometheus.io/scrape: "true"
  labels:
    app: thanos-store
  name: thanos-store
spec:
  ports:
  - port: 10901
    protocol: TCP
    targetPort: grpc
  selector:
    app: thanos-store
  sessionAffinity: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store
  labels:
    app: thanos-store
spec:
  podManagementPolicy: Parallel
  replicas: 2
  serviceName: thanos-store
  selector:
    matchLabels:
      app: thanos-store
  template:
    metadata:
      labels:
        app: thanos-store
    spec:
      containers:
      - name: thanos-store
        image: improbable/thanos:master-2019-06-28-106c5adb
        args:
        - store
        - --log.level=info
        - --data-dir=/var/thanos/store
        - --objstore.config-file=/etc/thanos/config.yaml
        - --index-cache-size=4GB
        - --chunk-pool-size=6GB
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        livenessProbe:
          httpGet:
            path: /metrics
            port: http
            scheme: HTTP
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 25
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: http
            scheme: HTTP
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
          failureThreshold: 25
        volumeMounts:
        - name: data
          mountPath: /var/thanos/store
        - name: config-volume
          mountPath: /etc/thanos
        resources:
          requests:
            cpu: 0m
            memory: 500Mi
          limits:
            memory: 4000Mi
      volumes:
      - name: config-volume
        secret:
          secretName: thanos-storage
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
