apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-rule-alerts
data:
  thanos-rule.yaml: |-
    groups:
    - name: thanos-rule
      rules:
      - alert: ThanosRuleIsDown
        expr: up{app="thanos-rule"} == 0 or absent(up{app="thanos-rule"})
        for: 10m
        annotations:
          summary: Thanos Rule is down
          impact: Telecom alerts are not working
          action: 'check {{ $labels.kubernetes_pod_name }} pod in {{ $labels.kubernetes_namespace}} namespace'
      - alert: ThanosRuleIsDroppingAlerts
        expr: rate(thanos_alert_queue_alerts_dropped_total{app="thanos-rule"}[5m]) > 0
        for: 10m
        annotations:
          summary: Thanos Rule is dropping alerts
          impact: Telecom alerts are not working
          action: 'check {{ $labels.kubernetes_pod_name }} pod logs in {{ $labels.kubernetes_namespace}} namespace'
