apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "10902"
    prometheus.io/scrape: "true"
  labels:
    app: thanos-store
  name: thanos-store
spec:
  ports:
  - port: 10901
    protocol: TCP
    targetPort: grpc
  selector:
    app: thanos-store
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-store
  labels:
    app: thanos-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thanos-store
  template:
    metadata:
      labels:
        app: thanos-store
    spec:
      containers:
      - name: thanos-store
        image: improbable/thanos:master-2019-02-06-33b57f6
        args:
        - store
        - --log.level=info
        - --data-dir=/var/thanos/store
        - --objstore.config-file=/etc/thanos/config.yaml
        - --cluster.disable
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /metrics
            port: http
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: http
            scheme: HTTP
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
          failureThreshold: 5
        volumeMounts:
        - name: data
          mountPath: /var/thanos/store
        - name: config-volume
          mountPath: /etc/thanos
        resources:
          requests:
            cpu: 50m
            memory: 2Gi
          limits:
            memory: 4Gi
      volumes:
      - name: data
        emptyDir: {}
      - name: config-volume
        secret:
          secretName: thanos-storage
