apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./thanos-query
  - ./thanos-rule
  - ./thanos-compact
  - ./thanos-store
  - ./prometheus
labels:
  - includeSelectors: true
    pairs:
      service: monitoring
