apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ./thanos-prometheus
commonLabels:
  service: monitoring
resources:
  - thanos-query.yaml
  - thanos-rule.yaml
images:
  - name: thanos
    newName: quay.io/thanos/thanos
    newTag: v0.11.0
configurations:
- thanos-prometheus/kustomizeconfig/ingressroute.yaml
