apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  service: monitoring
resources:
  - prometheus.yaml
  - thanos-compact.yaml
  - thanos-query.yaml
  - thanos-rule.yaml
  - thanos-store.yaml
images:
  - name: thanos
    newName: improbable/thanos
    newTag: master-2019-06-28-106c5adb
  - name: prometheus
    newName: prom/prometheus
    newTag: v2.10.0
