apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  template:
    spec:
      containers:
      - name: thanos-sidecar
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/secrets/service-account/credentials.json"
        volumeMounts:
        - name: thanos-storage
          mountPath: /etc/secrets/service-account/credentials.json
          subPath: credentials.json
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-compact
spec:
  template:
    metadata:
      name: thanos-compact
    spec:
      containers:
      - name: thanos-compact
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/secrets/service-account/credentials.json"
        volumeMounts:
        - name: thanos-storage
          mountPath: /etc/secrets/service-account/credentials.json
          subPath: credentials.json
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-store
  labels:
    app: thanos-store
spec:
  template:
    spec:
      containers:
      - name: thanos-store
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/secrets/service-account/credentials.json"
        volumeMounts:
        - name: thanos-storage
          mountPath: /etc/secrets/service-account/credentials.json
          subPath: credentials.json
