apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base/
#  - github.com/utilitywarehouse/thanos-manifests/base
resources:
  - prometheus-ingress.yaml
  - thanos-query-ingress.yaml
  - thanos-rule-ingress.yaml
patchesStrategicMerge:
  - gcp-credentials-patch.yaml
  - prometheus.yaml
  - thanos-rule.yaml
secretGenerator:
  # description: credentials for access to object storage
  # used-by: Prometheus, Thanos Store, Thanos Compact
  - name: thanos-storage
    type: Opaque
    files:
      - credentials.json=secrets/credentials.json
configMapGenerator:
  # description: application alerts handled by thanos-rule
  # used-by: Thanos Rule
  - name: alerts
    files:
      - prometheus-alerts.yaml=resources/prometheus-alerts.yaml
  # description: Prometheus configuration
  # used-by: Prometheus
  - name: prometheus
    files:
      - prometheus.yaml.tmpl=resources/prometheus.yaml.tmpl
  # description: Alerts to monitor Thanos infrastructure
  # used-by: Prometheus
  - name: thanos-rule-alerts
    files:
      - thanos-rule.yaml=resources/thanos-rule-alerts.yaml
  # description: Discovery config for TQ instances used to evaluate alert rules
  # used-by: Thanos Rule
  - name: thanos-rule
    files:
      - query-sd.yaml=resources/query-sd.yaml
  # description: config for access to object storage
  # used-by: Prometheus, Thanos Store, Thanos Compact
  - name: thanos-storage
    files:
      - config.yaml=resources/thanos-storage.yaml
  # description: Discovery config of Prometheus instances to aggregate query
  #   results
  # used-by: Thanos Query
  - name: thanos-query
    files:
      - store-sd.yaml=resources/store-sd.yaml
