apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: thanos-rule
  labels:
    kubernetes.io/ingress.class: traefik-private
  annotations:
    external-dns.alpha.kubernetes.io/target: load-balancer.overlay.gcp.example.com
spec:
  rules:
  - host: thanos-rule.overlay.gcp.example.com
    http:
      paths:
      - backend:
          serviceName: thanos-rule
          servicePort: 10902
        path: /
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-rule
spec:
  template:
    spec:
      containers:
      - name: thanos-rule
        env:
        - name: ALERTMANAGER_URL
          value: "dns+http://alertmanager.overlay-namespace"
        - name: THANOS_QUERY_URL
          value: "https://thanos-query.overlay.example.com"
